### ISSUE TITLE
Simulación del datos de carros en el parqueo

### ISSUE THREAD

**Issue by Carlosc23** [Carlosc23/parking-tool-back#18]
Generar una pequeña simulación para llenar los diferentes campos del json a subir en los request de parqueo lleno y vacío.

'time':{
            'check_in': '3:30',
            'departure':'3:45'
        },
        'vehicle':{
            'color':'blue',
            'brand':'mazda',
            'specialn':False,
            'type':'moto'
        },
        'position':''

**Comment by jorge97710** [comment]
Falta subir la union con los sensores. problemas por bugs 



[prueba.zip](https://github.com/Carlosc23/parking-tool-back/files/3136475/prueba.zip)
